[package]
name = "tfcsite-rs"
version = "0.1.2"
edition = "2021"

[dependencies]
tokio = { version = "1.39", features = ["full"] }
axum = "0.7"
tower-http = {  version = "0.5", features = ["compression-zstd", "fs", "redirect", "trace"] }
maud = "0.26"

tracing = "0.1"
tracing-subscriber = "0.3"