apiVersion: v1
kind: Service
metadata:
  name: {{ template "tfcsite.fullname" . }}
  labels:
    app: {{ template "tfcsite.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: {{ template "tfcsite.fullname" . }}
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  type: ClusterIP
  selector:
      app: {{ template "tfcsite.fullname" . }}
  ports:
    - name: tfcsite
      port:  80
      targetPort: web
      protocol: TCP